package oncue.svc.funnel
package agent
package nginx

import util.matching.Regex
import scalaz.\/
import journal.Logger

/**
 * This parser is designed to extract the meaingfull values
 * from the output generated by the stub_status nginx module:
 * http://nginx.org/en/docs/http/ngx_http_stub_status_module.html
 */
object Parser {

  private val log = Logger[Parser.type]

  private[nginx] val activeR = """^Active connections:\s+(\d+)\s+""".r
  private[nginx] val handledR = """^\s+(\d+)\s+(\d+)\s+(\d+)\s+""".r
  private[nginx] val currentR = """^Reading:\s+(\d+).*Writing:\s+(\d+).*Waiting:\s+(\d+)\s+""".r

  def parse(input: String): Throwable \/ Stats = \/.fromTryCatchNonFatal {
    val Array(line1, line2, line3, line4) = input.split('\n')

    val activeR(connections)                 = line1
    val handledR(accepts, handled, requests) = line3
    val currentR(reading, writing, waiting)  = line4

    Stats(
      connections.toLong,
      accepts.toLong,
      handled.toLong,
      requests.toLong,
      reading.toLong,
      writing.toLong,
      waiting.toLong)
  }
}
